name: Benchmark

on:
  workflow_dispatch:
    input: {}
  push:
    branches:
      - "main"

jobs:
  bench:
    name: Generate Benchmark
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        go:
          - "1.18"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Benchmark
        run: go test -bench=. -benchmem ./...

      - name: Push Result
        run: |
          git commit -am "[Action] Benchmark results"
          git push
